CREATE DATABASE IF NOT EXISTS meubanco
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE meubanco;

CREATE TABLE IF NOT EXISTS mensagens (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL,
  comentario TEXT NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
